[package]
name = "judge0-rs"
version = "0.0.0"
edition = "2021"

[dependencies]
http = "0.2.9"
reqwest = { version = "0.11.16", features = ["json"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
