name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    runs-on: macos-latest

    env:
      RUSTFLAGS: --deny warnings

    steps:
      - uses: actions/checkout@v2

      - name: Download actionlint
        id: actionlint
        run:
          bash <(curl
          https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow
        run: ${{ steps.actionlint.outputs.executable }} -color

      - name: Install rust toolchain components
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          override: true
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Info
        run: |
          rustup --version
          cargo --version
          cargo clippy --version

      - name: Forbid
        run: |
          brew install ripgrep
          ./bin/forbid

      - name: Build
        run: cargo build --workspace --all-features --all-targets

      - name: Clippy
        run: cargo clippy --all-targets --all-features

      - name: Check Lockfile
        run: cargo update --locked --package judge0-rs

      - name: Format
        run: cargo fmt --all -- --check

      - name: Test
        run: cargo test --workspace --all-features --all-targets
